// ---------------------------------------------------------------------------
// Latest updates (news) and Guidance resources, per hazard.
//
// These are REAL, working links to official / authoritative pages (verified
// live). Cards render as publisher link-previews (favicon + source + headline)
// rather than fabricated article photos, because SG news/gov sites block image
// hotlinking and most expose no usable cover image.
// ---------------------------------------------------------------------------

import type { Hazard } from "./scenario";
import type { Language } from "./types";

export interface MediaItem {
  id: string;
  source: string; // publisher, e.g. "NEA", "MOH", "CDC"
  title: string; // real page / article headline
  url: string; // verified-live link
  format: "Update" | "Article";
  time?: string; // shown on "Latest updates" cards
}

export const news: Record<Hazard, MediaItem[]> = {
  covid: [
    {
      id: "c-moh-update",
      source: "MOH",
      title: "Update on the COVID-19 situation",
      time: "13 May 2025",
      format: "Update",
      url: "https://www.moh.gov.sg/newsroom/update-on-covid-19-situation-/",
    },
    {
      id: "c-cda-bulletin",
      source: "CDA",
      title: "Weekly Infectious Diseases Bulletin",
      time: "Updated weekly",
      format: "Update",
      url: "https://www.cda.gov.sg/resources/weekly-infectious-diseases-bulletin-2025/",
    },
    {
      id: "c-moh-hub",
      source: "MOH",
      title: "COVID-19: current situation and guidance",
      time: "Live",
      format: "Update",
      url: "https://www.moh.gov.sg/covid-19",
    },
  ],
  dengue: [
    {
      id: "d-nea-surge",
      source: "NEA",
      title: "Vigilance needed to prevent a dengue surge in 2025",
      time: "25 May 2025",
      format: "Update",
      url: "https://www.nea.gov.sg/media/news/news/index/dengue-outbreaks-averted-in-2023-and-2024---vigilance-needed-to-prevent-dengue-surge-in-2025",
    },
    {
      id: "d-nea-cases",
      source: "NEA",
      title: "Latest dengue cases and active clusters",
      time: "Updated weekly",
      format: "Update",
      url: "https://www.nea.gov.sg/dengue-zika/dengue/dengue-cases",
    },
  ],
};

export interface VideoItem {
  id: string; // stable id, e.g. "self-test-kit" (referenced by the AI chat)
  title: string; // section heading shown above the player
  source: string; // publisher / channel, e.g. "The Straits Times"
  src: string; // self-hosted video file under /public
  poster: string; // self-hosted poster image shown before play
  // One line on what the video teaches — given to the AI so it knows when to
  // surface this video in a reply.
  about: string;
  // Languages (besides English) with a pre-rendered dub MP3 sitting next to
  // the video, named "<basename>.<lang>.mp3". When the app language is one of
  // these, the player mutes the original and plays the dub track in sync.
  // Generated by scripts/dub.mjs.
  dubLangs?: Language[];
}

// Public URL for a media file in the Supabase "media" bucket (under videos/).
// Files are uploaded by scripts/upload-media.mjs. Falls back to the local
// /public copy if the Supabase URL env var is missing (e.g. before setup).
const MEDIA_BUCKET = "media";
function mediaUrl(file: string): string {
  const base = process.env.NEXT_PUBLIC_SUPABASE_URL;
  return base
    ? `${base}/storage/v1/object/public/${MEDIA_BUCKET}/videos/${file}`
    : `/videos/${file}`;
}

// A featured how-to video per hazard, rendered as a playable card below the
// guidance carousel. Served from Supabase Storage (see mediaUrl). Only hazards
// with an entry show the section.
export const videos: Partial<Record<Hazard, VideoItem>> = {
  covid: {
    id: "self-test-kit",
    title: "Self-test kit tutorial",
    source: "The Straits Times",
    src: mediaUrl("self-test-kit.mp4"),
    poster: mediaUrl("self-test-kit.webp"),
    about:
      "Step-by-step how to use a COVID-19 antigen rapid test (ART) self-test kit at home — swabbing, reading the result, and disposal.",
    dubLangs: ["id", "ms", "tl", "zh", "my"],
  },
};

/** All videos as a flat list, regardless of hazard. */
export const allVideos: VideoItem[] = Object.values(videos).filter(
  (v): v is VideoItem => Boolean(v)
);

/** Look up a video by its stable id (used to render a video the AI suggested). */
export function findVideo(id: string): VideoItem | null {
  return allVideos.find((v) => v.id === id) ?? null;
}

/** Path of the dubbed MP3 for a video + language, e.g. ".../x.mp4" -> ".../x.id.mp3". */
export function dubTrackPath(src: string, lang: Language): string {
  return src.replace(/\.mp4$/, `.${lang}.mp3`);
}

export const guidance: Record<Hazard, MediaItem[]> = {
  covid: [
    {
      id: "cg-healthhub-flu",
      source: "HealthHub",
      title: "Influenza vaccine: what you need to know",
      format: "Article",
      url: "https://www.healthhub.sg/medication-devices-and-treatment/medications/influenza-vaccine",
    },
    {
      id: "cg-cdc-65",
      source: "CDC",
      title: "Flu and people 65 years and older",
      format: "Article",
      url: "https://www.cdc.gov/flu/highrisk/65over.htm",
    },
    {
      id: "cg-who-covid",
      source: "WHO",
      title: "COVID-19: advice for the public",
      format: "Article",
      url: "https://www.who.int/health-topics/coronavirus",
    },
  ],
  dengue: [
    {
      id: "dg-nea-prevent",
      source: "NEA",
      title: "Prevent dengue: do the 5-step Mozzie Wipeout",
      format: "Article",
      url: "https://www.nea.gov.sg/dengue-zika",
    },
    {
      id: "dg-cdc-signs",
      source: "CDC",
      title: "Dengue symptoms and warning signs",
      format: "Article",
      url: "https://www.cdc.gov/dengue/signs-symptoms/index.html",
    },
    {
      id: "dg-who-fact",
      source: "WHO",
      title: "Dengue and severe dengue — fact sheet",
      format: "Article",
      url: "https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue",
    },
    {
      id: "dg-cdc-prevent",
      source: "CDC",
      title: "Preventing dengue: protect against mosquito bites",
      format: "Article",
      url: "https://www.cdc.gov/dengue/prevention/index.html",
    },
  ],
};
